name: Test
on:
  - push
  - pull_request
jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "3.3 on Windows"
            ruby-version: "3.3"
            runs-on: "windows-latest"
          - name: "3.3 on Windows + Thread"
            ruby-version: "3.3"
            runs-on: "windows-latest"
            testopts: "--parallel=thread"
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          bundle install
      - name: Test
        run: |
          bundle exec rake
        env:
          RUBYOPT: ${{ matrix.rubyopt }}
          TESTOPTS: ${{ matrix.testopts }}
